// stellavault draft — Express: 지식에서 초안 생성
// 카파시 자가 컴파일 → 외부 표현의 출구
// 두 가지 모드: rule-based (무료) + --ai (Claude API로 실제 글 생성)

import chalk from 'chalk';
import { loadConfig } from '@stellavault/core';
import { generateDraft } from '@stellavault/core/intelligence/draft-generator';

export async function draftCommand(topic: string | undefined, options: { format?: string; ai?: boolean }) {
  const config = loadConfig();

  if (!config.vaultPath) {
    console.error(chalk.red('No vault configured. Run `stellavault init` first.'));
    process.exit(1);
  }

  const format = (options.format ?? 'blog') as 'blog' | 'report' | 'outline';

  try {
    // Step 1: rule-based 초안 생성 (스캐폴딩 + 소스 수집)
    const result = generateDraft(config.vaultPath, { topic, format }, config.folders);

    if (options.ai) {
      // Step 2: --ai 모드 → Claude API로 실제 글 생성
      console.log(chalk.dim('  AI mode: generating with Claude...'));
      await enhanceWithAI(config.vaultPath, result.filePath, topic ?? 'knowledge', format);
    }

    console.log(chalk.green(`Draft generated: ${result.title}`));
    console.log(chalk.dim(`  Format: ${format}`));
    console.log(chalk.dim(`  Mode: ${options.ai ? 'AI-enhanced (Claude)' : 'rule-based'}`));
    console.log(chalk.dim(`  Saved: ${result.filePath}`));
    console.log(chalk.dim(`  Words: ${result.wordCount}`));
    console.log(chalk.dim(`  Sources: ${result.sourceCount} documents`));
    if (result.concepts.length > 0) {
      console.log(chalk.dim(`  Concepts: ${result.concepts.join(', ')}`));
    }
    console.log('');
    console.log(chalk.dim(`Next steps:`));
    console.log(chalk.dim(`  Edit in Obsidian, then promote:`));
    console.log(chalk.cyan(`  stellavault promote ${result.filePath} --to literature`));
    if (!options.ai) {
      console.log(chalk.dim(`  Or use --ai for Claude-enhanced draft, or MCP generate-draft in Claude Code.`));
    }
  } catch (err) {
    console.error(chalk.red(err instanceof Error ? err.message : 'Draft generation failed'));
    process.exit(1);
  }
}

async function enhanceWithAI(vaultPath: string, draftPath: string, topic: string, format: string) {
  const { readFileSync, writeFileSync } = await import('node:fs');
  const { resolve } = await import('node:path');
  const fullPath = resolve(vaultPath, draftPath);
  const scaffold = readFileSync(fullPath, 'utf-8');

  // Extract source excerpts from scaffold
  const excerpts = scaffold
    .split('\n')
    .filter(l => l.startsWith('> '))
    .map(l => l.slice(2))
    .join('\n');

  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    console.error(chalk.yellow('  ANTHROPIC_API_KEY not set. Falling back to rule-based draft.'));
    console.error(chalk.yellow('  Set it with: export ANTHROPIC_API_KEY=sk-ant-...'));
    return;
  }

  try {
    const Anthropic = (await import('@anthropic-ai/sdk')).default;
    const client = new Anthropic({ apiKey });

    const message = await client.messages.create({
      model: 'claude-sonnet-4-20250514',
      max_tokens: 4096,
      messages: [{
        role: 'user',
        content: `You are writing a ${format} about "${topic}" based ONLY on the following knowledge notes.
Do not add information beyond what's in the notes. Write in the same language as the source material.
Use [[title]] wikilink format for citations.

SOURCE NOTES:
${excerpts.slice(0, 8000)}

Write a complete, well-structured ${format}. No TODO placeholders.`,
      }],
    });

    const aiContent = message.content[0];
    if (aiContent.type === 'text') {
      const enhanced = `---
title: "Draft: ${topic}"
type: draft
format: ${format}
mode: ai-enhanced
sources: ${excerpts.split('\n').length} excerpts
created: ${new Date().toISOString()}
---

${aiContent.text}

---
*Generated by \`stellavault draft --ai\` using Claude API at ${new Date().toISOString()}*
`;
      writeFileSync(fullPath, enhanced, 'utf-8');
    }
  } catch (err) {
    console.error(chalk.yellow(`  AI enhancement failed: ${err instanceof Error ? err.message : 'unknown'}. Keeping rule-based draft.`));
  }
}
