// Design Ref: §4 — SVG 프로필 카드 생성
// 레이더 차트 (상위 6 클러스터) + 워드클라우드 (상위 20 태그) + 통계

interface ClusterInfo {
  label: string;
  color: string;
  nodeCount: number;
}

interface CardData {
  title: string;
  documentCount: number;
  clusterCount: number;
  edgeCount: number;
  clusters: ClusterInfo[];
  topTags: Array<{ tag: string; count: number }>;
}

export function generateProfileCardSVG(data: CardData): string {
  const W = 800, H = 420;
  const top6 = data.clusters.slice(0, 6);
  const maxCount = Math.max(1, ...top6.map(c => c.nodeCount));

  // 레이더 차트 계산
  const radarCx = 200, radarCy = 220, radarR = 100;
  const radarPoints = top6.map((c, i) => {
    const angle = (Math.PI * 2 * i) / top6.length - Math.PI / 2;
    const r = radarR * (c.nodeCount / maxCount);
    return {
      x: radarCx + r * Math.cos(angle),
      y: radarCy + r * Math.sin(angle),
      labelX: radarCx + (radarR + 20) * Math.cos(angle),
      labelY: radarCy + (radarR + 20) * Math.sin(angle),
      label: c.label.split(',')[0].trim().slice(0, 12),
      color: c.color,
    };
  });

  const radarPath = radarPoints.map((p, i) => `${i === 0 ? 'M' : 'L'}${p.x},${p.y}`).join(' ') + 'Z';

  // 레이더 그리드 (3단계)
  const gridPaths = [0.33, 0.66, 1].map(scale => {
    return top6.map((_, i) => {
      const angle = (Math.PI * 2 * i) / top6.length - Math.PI / 2;
      const x = radarCx + radarR * scale * Math.cos(angle);
      const y = radarCy + radarR * scale * Math.sin(angle);
      return `${i === 0 ? 'M' : 'L'}${x},${y}`;
    }).join(' ') + 'Z';
  });

  // 워드클라우드
  const tags20 = data.topTags.slice(0, 20);
  const maxTagCount = Math.max(1, ...tags20.map(t => t.count));

  const tagElements = tags20.map((t, i) => {
    const size = 10 + 14 * (t.count / maxTagCount);
    const col = i % 2 === 0 ? Math.floor(i / 2) : Math.floor(i / 2);
    const row = i % 2;
    const x = 480 + (col % 5) * 60;
    const y = 140 + row * 30 + Math.floor(i / 10) * 70;
    const opacity = 0.5 + 0.5 * (t.count / maxTagCount);
    return `<text x="${x}" y="${y}" font-size="${size}" fill="#88aaff" opacity="${opacity}" font-family="monospace">#${escapeXml(t.tag)}</text>`;
  }).join('\n    ');

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}">
  <defs>
    <linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="#0d1028"/>
      <stop offset="100%" stop-color="#050510"/>
    </linearGradient>
    <linearGradient id="radar-fill" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="#6366f1" stop-opacity="0.3"/>
      <stop offset="100%" stop-color="#06b6d4" stop-opacity="0.15"/>
    </linearGradient>
  </defs>

  <!-- Background -->
  <rect width="${W}" height="${H}" rx="16" fill="url(#bg)"/>
  <rect width="${W}" height="${H}" rx="16" fill="none" stroke="#6366f140" stroke-width="1"/>

  <!-- Header -->
  <text x="30" y="40" font-size="20" font-weight="700" fill="#c0c0f0" font-family="system-ui, sans-serif">
    🧠 ${escapeXml(data.title)}
  </text>
  <text x="30" y="65" font-size="13" fill="#556" font-family="monospace">
    ${data.documentCount} documents · ${data.clusterCount} clusters · ${data.edgeCount} connections
  </text>
  <line x1="30" y1="80" x2="${W - 30}" y2="80" stroke="#6366f120" stroke-width="1"/>

  <!-- Radar Chart -->
  <text x="${radarCx}" y="105" font-size="11" fill="#667" text-anchor="middle" font-family="system-ui">KNOWLEDGE DISTRIBUTION</text>

  <!-- Grid -->
  ${gridPaths.map(p => `<path d="${p}" fill="none" stroke="#6366f115" stroke-width="0.5"/>`).join('\n  ')}

  <!-- Radar axes -->
  ${radarPoints.map(p => `<line x1="${radarCx}" y1="${radarCy}" x2="${p.labelX}" y2="${p.labelY}" stroke="#6366f110" stroke-width="0.5"/>`).join('\n  ')}

  <!-- Radar shape -->
  <path d="${radarPath}" fill="url(#radar-fill)" stroke="#818cf8" stroke-width="1.5"/>

  <!-- Radar dots + labels -->
  ${radarPoints.map(p => `
  <circle cx="${p.x}" cy="${p.y}" r="3" fill="${p.color}"/>
  <text x="${p.labelX}" y="${p.labelY + 4}" font-size="9" fill="#889" text-anchor="middle" font-family="monospace">${escapeXml(p.label)}</text>
  `).join('')}

  <!-- Word Cloud -->
  <text x="580" y="105" font-size="11" fill="#667" text-anchor="middle" font-family="system-ui">TOP TOPICS</text>
  <rect x="440" y="115" width="320" height="240" rx="8" fill="#6366f108"/>
    ${tagElements}

  <!-- Footer -->
  <text x="${W / 2}" y="${H - 15}" font-size="10" fill="#334" text-anchor="middle" font-family="monospace">
    Generated by Stellavault
  </text>
</svg>`;
}

function escapeXml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}
